id = "xml"
name = "XML"
description = "XML syntax support."
version = "0.0.8"
schema_version = 1
authors = ["sweetppro"]
repository = "https://github.com/sweetppro/zed-xml"

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
commit = "863dbc381f44f6c136a399e684383b977bb2beaa"
path = "xml"
